### ISSUE TITLE
Handbrake needs exception

### ISSUE THREAD

**Issue by afontenot** [thestinger/paxd#36]
Handbrake 0.10.1-2 from the Arch repos crashes immediately on launch because of mprotect : 

    (handbrake:10354): GLib-ERROR **: file gthread-posix.c: line 1182 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'

Can you add an `em` exception for `/usr/bin/handbrake` in paxd? Thanks for your work.

**Comment by thestinger** [comment]
Fixed by f7c083c8ceabde03d42f1aebe2d7019a4f5d922d.
