### ISSUE TITLE
Quassel and Steam binaries should be added

### ISSUE THREAD

**Issue by tancrackers** [thestinger/paxd#40]
There's a rule for:
em  /usr/bin/quasselcore
However, I installed quassel-monolithic which has the file /usr/bin/quassel instead.
This file should be added to paxd.conf

As for Steam, I only got the gui working by adding:
m ~/.local/share/Steam/ubuntu12_32/steam
m ~/.steam/steam/ubuntu12_32/gameoverlayui
m ~/.steam/steam/ubuntu12_32/steamwebhelper
m ~/.steam/steam/ubuntu12_32/streaming_client
m ~/.steam/steam/SteamApps/*/*/hl2_linux

**Comment by thestinger** [comment]
Steam works for me without these exceptions. The Half Life 2 one is probably required though.

**Comment by thestinger** [comment]
Are you using the user service? You should add these kinds of exceptions there.

**Comment by tancrackers** [comment]
I did. All is good
