### ISSUE TITLE
Visual-studio-code?

### ISSUE THREAD

**Issue by tancrackers** [thestinger/paxd#47]
In the paxd.conf file, the path is:
em  /opt/VSCode/Code
However, this is the path that I see in my visual-studio-code installation:
/opt/visual-studio-code/Code

**Comment by juanfra684** [comment]
There are two different packages for Visual Studio Code:
https://aur.archlinux.org/packages/visual-studio-code/
https://aur.archlinux.org/packages/vscode-bin/
