### ISSUE TITLE
Python2.7 denied RWX mmap

### ISSUE THREAD

**Issue by g4jc** [thestinger/paxd#49]
Hello,
I've tried adding "em /usr/bin/python2.7" to the paxd.conf, but this error persists when attempting to compile this package: https://aur.archlinux.org/packages/tahoe-lafs/

[ 5826.002201] grsec: (default:D:/) denied RWX mmap of <anonymous mapping> by /usr/bin/python2.7[python2:19899] uid/euid:1000/1000 gid/egid:100/100, parent /usr/bin/makepkg[makepkg:19819] uid/euid:1000/1000 gid/egid:100/100
[ 5826.002209] python2[19899]: segfault at 0 ip 0000032bc250adcb sp 0000039103980918 error 6 in libffi.so.6.0.4[32bc2505000+8000]
[ 5826.003455] systemd-coredump[19920]: Failed to get COMM, falling back to the command line.
[ 5826.003465] systemd-coredump[19920]: Failed to get EXE.

This might actually be a bug in libffi, but I figured I'd post here first before going upstream.

**Comment by thestinger** [comment]
Can't reproduce this and marking it with an MPROTECT exception should work fine.
