### ISSUE TITLE
A few new paxd settings from downstream

### ISSUE THREAD

**Issue by g4jc** [thestinger/paxd#50]
Since the downstream fork contains deletions I figured it would be best to post these setting here vs in a pull request.

Fixes:
m /usr/bin/cairo-dock
m  /usr/lib/lmc/lan-messenger
m /usr/bin/xiphos
m /usr/bin/zpaq
# browsers

pem /usr/lib/iceweasel/iceweasel
em  /usr/lib/iceweasel/plugin-container
em  /usr/lib/icecat/icecat
em  /usr/lib/icecat/plugin-container
pem /usr/lib/icedove/icedove
em  /usr/lib/icedove/plugin-container
# games

emr /usr/bin/pyrogenesis
emr /usr/bin/hwengine
em /opt/ryzom/ryzom_client
em /usr/bin/bzflag
em /usr/bin/minetest
em /usr/bin/opencity
# replicant

em /opt/replicant-sdk/tools/emulator-arm
em /opt/replicant-sdk/tools/emulator-x86
em /opt/replicant-sdk/platform-tools/adb

**Comment by thestinger** [comment]
The grsecurity and PaX patches are no longer public, so paxd maintenance has ended.
