### ISSUE TITLE
Denied RWX mmap by nautilus

### ISSUE THREAD

**Issue by neitsab** [thestinger/paxd#64]
```
grsec: denied RWX mmap of <anonymous mapping> by /usr/bin/nautilus[nautilus:1347] uid/euid:1000/1000 gid/egid:1000/1000, parent /usr/lib/gnome-session/gnome-session-binary[gnome-session-b:1227] uid/euid:1000/1000 gid/egid:1000/1000
```

This comes right after two fuse auto-load errors like the ones reported [here](https://forums.grsecurity.net/viewtopic.php?f=3&t=4352).

Thanks!

**Comment by thestinger** [comment]
The grsecurity and PaX patches are no longer public, so paxd maintenance has ended.
