### ISSUE TITLE
gedit, grep & tor-browser

### ISSUE THREAD

**Issue by neitsab** [thestinger/paxd#66]
```
grsec: denied RWX mmap of <anonymous mapping> by /usr/bin/gedit[gedit:2271] uid/euid:1000/1000 gid/egid:1000/1000, parent /usr/lib/systemd/systemd[systemd:1167] uid/euid:1000/1000 gid/egid:1000/1000
```

```
grsec: denied RWX mmap of <anonymous mapping> by /usr/bin/grep[grep:10338] uid/euid:1000/1000 gid/egid:1000/1000, parent /usr/bin/pacaur[pacaur:10334] uid/euid:1000/1000 gid/egid:1000/1000
```

> **Note**: The grep/pacaur one triggers a `more alerts, logging disabled for 10 seconds`.

```
grsec: denied RWX mmap of <anonymous mapping> by /opt/.tor-browser-fr/INSTALL/Browser/firefox[firefox:23086] uid/euid:1000/1000 gid/egid:1000/1000, parent /usr/bin/bash[bash:23073] uid/euid:1000/1000 gid/egid:1000/1000
```

**Note**: I use a non-standard location for the `.tor-browser-fr/` folder: normally it goes under `~/`, but I moved it under `/opt/` and symlinked it back because I use the `noexec` mount option for `/home` and didn't want to remove it just for TBB. I understand I'll have to handle it myself but I wanted to document it just in case.

Thanks

**Comment by thestinger** [comment]
The grsecurity and PaX patches are no longer public, so paxd maintenance has ended.
