### ISSUE TITLE
collected Arch Linux issue reports

### ISSUE THREAD

**Issue by thestinger** [thestinger/paxd#81]
* php https://bugs.archlinux.org/task/48279
* evolution https://bugs.archlinux.org/task/48442
* nessus https://bugs.archlinux.org/task/48504
* seamonkey https://bugs.archlinux.org/task/49240
* spectacle https://bugs.archlinux.org/task/49462
* ~~~firefox https://bugs.archlinux.org/task/51171~~~
* awesome wm https://bugs.archlinux.org/task/51234
* spideroak one https://bugs.archlinux.org/task/51645
* kwin wayland https://bugs.archlinux.org/task/51705
* plasmashell https://bugs.archlinux.org/task/51784
* mongodb https://bugs.archlinux.org/task/52064

**Comment by HighIO** [comment]
nomacs  image viewer also need # setfattr -n user.pax.flags -v em /usr/bin/nomacs
THX

**Comment by thestinger** [comment]
The grsecurity and PaX patches are no longer public, so paxd maintenance has ended.
