### ISSUE TITLE
is gcc exception really needed?

### ISSUE THREAD

**Issue by pysli** [thestinger/paxd#86]
I wonder if gcc exceptions are really needed. When disabled I can still compile kernel and some packages without issues. 

gcc exceptions aren't used in https://grsecurity.net/paxctld/paxctld_1.2.1.orig.tar.gz or https://github.com/subgraph/paxrat/blob/master/paxrat.conf

**Comment by thestinger** [comment]
Yes, it's needed. It even documents the reason. The paxctld package doesn't attempt to be nearly as complete as this.
